# Generated by Django 3.0.5 on 2020-04-09 15:27

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import dookan.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Brand Name')),
                ('publish', models.BooleanField(default=True, verbose_name='Publish')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dookan_brand_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dookan_brand_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=55, verbose_name='Category Name')),
                ('publish', models.BooleanField(default=True, verbose_name='Publish')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dookan_category_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dookan.Category', verbose_name='Parent')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dookan_category_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Image Title')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/images/'), upload_to=dookan.files.image_upload_path, verbose_name='Image')),
                ('md_image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/images/'), upload_to=dookan.files.md_image_upload_path, verbose_name='Medium Image')),
                ('sm_image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/images/'), upload_to=dookan.files.sm_image_upload_path, verbose_name='Small Image')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dookan_media_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dookan_media_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Product Type')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dookan_producttype_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dookan_producttype_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Product Name')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Model')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weight')),
                ('unit', models.CharField(blank=True, choices=[('kg', 'KG'), ('gm', 'GM'), ('mg', 'MG'), ('m', 'Meter'), ('cm', 'Centimeter'), ('mm', 'Millimeter')], max_length=50, null=True, verbose_name='Unit')),
                ('material', models.CharField(blank=True, max_length=80, null=True, verbose_name='Material')),
                ('size', models.CharField(blank=True, choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('xxl', 'Double Extra Large')], max_length=50, null=True, verbose_name='Size')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Default Price')),
                ('discount_percentage', models.IntegerField(blank=True, null=True, verbose_name='Discount Percentage')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Discount Price')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('product_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Product Key')),
                ('publish', models.BooleanField(default=True, verbose_name='Publish')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dookan.Brand', verbose_name='Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dookan.Category', verbose_name='Product Category')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dookan_product_created', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(to='dookan.Media', verbose_name='Product Images')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_products', to='dookan.ProductType', verbose_name='Product Type')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dookan_product_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=15, verbose_name='Coupon Code')),
                ('amount', models.IntegerField()),
                ('amount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=15, verbose_name='Amount Type')),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='dookan.Category')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dookan_coupon_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dookan_coupon_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
