# Generated by Django 3.0.5 on 2020-04-05 12:22

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import dookan.files


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dookan', '0002_auto_20200404_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/images/'), upload_to=dookan.files.image_upload_path, verbose_name='Image')),
                ('md_image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/images/'), upload_to=dookan.files.md_image_upload_path, verbose_name='Medium Image')),
                ('sm_image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/images/'), upload_to=dookan.files.sm_image_upload_path, verbose_name='Small Image')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dookan_media_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dookan_media_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
