# Generated by Django 3.0.5 on 2020-04-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dookan', '0002_cart_customer_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ACtive'),
        ),
    ]
